export default [
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm0_points',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm1_points',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm2_points',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm3_points',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm4_points',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
];
