export default [
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'wld_adm0',
    maxzoom: 22,
    minzoom: 0,
    source: 'wld_adm',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'wld_adm1',
    maxzoom: 22,
    minzoom: 0,
    source: 'wld_adm',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'wld_adm2',
    maxzoom: 22,
    minzoom: 0,
    source: 'wld_adm',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'wld_adm3',
    maxzoom: 22,
    minzoom: 0,
    source: 'wld_adm',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'wld_adm4',
    maxzoom: 22,
    minzoom: 0,
    source: 'wld_adm',
    source_name: 'Atlas Default',
  },
];
