export default [
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm0_lines',
    maxzoom: 22,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm1_lines',
    maxzoom: 22,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm2_lines',
    maxzoom: 22,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm3_lines',
    maxzoom: 22,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'adm4_lines',
    maxzoom: 22,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
];
