export default [
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'osm_rivers_river',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'osm_roads_trunk',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'osm_roads_primary',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'osm_roads_secondary',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
  {
    description: '',
    fields: { name: 'String', pcode: 'String' },
    id: 'osm_roads_tertiary',
    maxzoom: 24,
    minzoom: 0,
    source: 'atlas',
    source_name: 'Atlas Default',
  },
];
