const defaults = {
  description: '',
  fields: { name: 'String' },
  maxzoom: 24,
  minzoom: 0,
  source: 'atlas',
  source_name: 'Atlas Default',
};

export default [
  { ...defaults, id: 'adm0_polygons' },
  { ...defaults, id: 'adm0_lines' },
  { ...defaults, id: 'adm1_lines' },
  { ...defaults, id: 'adm2_lines' },
  { ...defaults, id: 'adm3_lines' },
  { ...defaults, id: 'adm4_lines' },
  { ...defaults, id: 'adm0_points' },
  { ...defaults, id: 'adm1_points' },
  { ...defaults, id: 'adm2_points' },
  { ...defaults, id: 'adm3_points' },
  { ...defaults, id: 'adm4_points' },
  { ...defaults, id: 'osm_water' },
  { ...defaults, id: 'osm_wetlands' },
  { ...defaults, id: 'osm_railways_all' },
  { ...defaults, id: 'osm_roads_trunk' },
  { ...defaults, id: 'osm_roads_primary' },
  { ...defaults, id: 'osm_roads_secondary' },
  { ...defaults, id: 'osm_roads_tertiary' },
  { ...defaults, id: 'osm_rivers_all' },
  { ...defaults, id: 'osm_airports_all' },
  { ...defaults, id: 'osm_education_facilities_all' },
  { ...defaults, id: 'osm_financial_services_all' },
  { ...defaults, id: 'osm_healthsites_all' },
  { ...defaults, id: 'osm_populated_places_city' },
  { ...defaults, id: 'osm_populated_places_town' },
  { ...defaults, id: 'osm_populated_places_village' },
  { ...defaults, id: 'osm_sea_ports_all' },
];
