- hosts: all
  tasks:
    - name: Add apt keys
      apt_key:
        url: '{{ item }}'
      loop:
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://nginx.org/keys/nginx_signing.key
    - name: Add apt repositories
      apt_repository:
        repo: '{{ item }}'
      loop:
        - deb https://repos.insights.digitalocean.com/apt/do-agent/ main main
        - deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x/ {{ ansible_distribution_release }} main
        - deb https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
    - name: Install apt packages
      apt:
        name:
          - build-essential
          - do-agent
          - nginx
          - nodejs
          - python
          - s3cmd
          - ufw
        state: latest
        update_cache: yes
    - name: Install npm packages
      npm:
        name: tileserver-gl-light
        global: yes
        state: latest
    - name: Enable firewall
      ufw:
        state: enabled
        rule: allow
        name: '{{ item }}'
      loop:
        - ssh
        - www secure
    - name: Copy s3cfg
      copy:
        src: ~/.s3cfg
        dest: ~/.s3cfg
    - name: Copy services
      copy:
        src: tileserver-gl.service
        dest: /etc/systemd/system/tileserver-gl.service
      notify: Restart systemd
    - name: Copy certificates
      copy:
        src: '~/.ssl/{{ item.src }}.pem'
        dest: '/etc/ssl/{{ item.dest }}.pem'
      loop:
        - { src: 'fieldmaps.io.private', dest: 'private/fieldmaps' }
        - { src: 'fieldmaps.io.public', dest: 'certs/fieldmaps' }
        - { src: 'cloudflare.public', dest: 'certs/cloudflare' }
      notify: Restart nginx
    - name: Copy nginx.conf
      copy:
        src: default.conf
        dest: /etc/nginx/conf.d/default.conf
      notify: Restart nginx
    - name: Sync tiles
      shell: s3cmd sync --delete-removed s3://data.fieldmaps.io/tiles/ /usr/share/tileserver-gl/
      register: result
      until: result.rc == 0
      notify: Restart tileserver-gl
  handlers:
    - name: Restart systemd
      systemd:
        daemon-reload: yes
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
    - name: Restart tileserver-gl
      service:
        name: tileserver-gl
        state: restarted
